### ISSUE TITLE
[Bug] method viewer overlapping of chars

### ISSUE THREAD

**Issue by AlexImmer** [HPI-SWA-Teaching/SWT15-Project-09#33]

**Comment by Chaoste** [comment]
SPluggableTextMorph>setText:

Creates a text morph class which sets the correct margin for the source code ("24")
[ "textMorph := self textMorphClass new" > "initialize" > "margins: leftOffset@0 ..." ]

Problem: Overwritten by "textMorph margins: (3@0 ..."
Solution: Check if textMorph margins is already set -> Otherwise use "3@0..."

TODO: Write SPluggableTextMorph(Plus) class comment (inclusive relation to SStickySourceCodeMorph)

**Comment by Chaoste** [comment]
TODO: Write test
